version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      args:
        BIN_NAME: transfer-legacy-api
    environment:
      - TL_BIND_ADDR=0.0.0.0
      - TL_PORT=8080
      - TL_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - redis
      - openbao
    ports:
      - "8080:8080"

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile
      args:
        BIN_NAME: transfer-legacy-worker
    command: ["/app/transfer-legacy-worker"]
    environment:
      - TL_BIND_ADDR=0.0.0.0
      - TL_PORT=8081
      - TL_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - redis
      - openbao

  redis:
    image: redis:7.2.13@sha256:7cf869be4d3d7956fb6dea29416f423f8b15f4f83581dee636591e11a520ac41
    command: ["redis-server", "--requirepass", "localdev", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"

  openbao:
    image: openbao/openbao:2.5.0-amd64@sha256:74a9997f0fc630f429fd71bdf2e7fffba39fe3024ca1ded9f094b15f7ea3f79e
    command: ["server", "-config=/openbao/config.hcl"]
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      - ./openbao/config.hcl:/openbao/config.hcl:ro
      - ./openbao/data:/openbao/data
